---
- block:
    - include: setup.yml
    - name: Create nodejs project
      shell: "oc new-project {{samples.nodejs.project}}"

    - name: Create app from template
      shell: "oc new-app --template={{samples.nodejs.template_name}} -n {{samples.nodejs.project}}"    

    - name: Ensure we are able to access the application via the exposed route
      uri:
        url: "http://nodejs-mongo-persistent-{{ samples.nodejs.project }}.apps.{{ cluster_id }}.{{ cluster_domain }}/"
        follow_redirects: none
        method: GET
      register: _result
      until: _result.status == 200
      retries: 720 
      delay: 5 # Every 5 seconds

    - include: cleanup.yml