---
- hosts: localhost
  connection: local
  vars_files:
    - vars/vsphere-homelab.yml
  tasks:
    - block:
        - name: Deploy cluster logging
          include_role: name=deploy-cluster-logging