---
- block:
    - include: setup.yml
    - name: Create springboot project
      shell: "oc new-project {{ samples.springboot.project }}"

    - name: Create camel app template
      shell: "oc create -f {{ samples.springboot.template_url }} -n {{ samples.springboot.project }}"    

    - name: Create camel app template
      shell: "oc new-app --template={{ samples.springboot.template_name }} -p GIT_REF={{samples.springboot.git.ref}} -p MAVEN_MIRROR_URL={{ samples.springboot.maven_mirror }} -p GIT_REPO={{samples.springboot.git.url}}"

    - name: Wait 1 min for app to build etc
      pause:
        minutes: 1

    - name: Wait for app to be running
      shell: "oc get pods -l app=s2i-fuse74-spring-boot-camel -n {{ samples.springboot.project }} --field-selector \"status.phase=Running\" -o name"
      register: podname
      until: podname.stdout_lines|length == 1
      retries: 10
      delay: 60
      
    - include: cleanup.yml